[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "comp0034-14Covid-1"
version = "2025.1"
description = "COMP0034 Coursework using 14-Covid-1 dataset"
readme = "README.md"
keywords = ["data-science", "sqlite", "database", "data-exploration"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent"
]
requires-python = ">=3.6"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pylint.'MESSAGES CONTROL']
disable=[
  'no-name-in-module',
  'redefined-outer-name',
  'unsupported-assignment-operation',
  'unsubscriptable-object',
  'unsubscriptable-object',
  'dangerous-default-value',
  'unused-argument',
  'not-callable',
  'unsupported-membership-test'
]

[tool.pytest.ini_options]
pythonpath = "src"